services:

  keelson-connector-camera-luxonis-thermal:
    build: .
    container_name: cam-luxonis-thermal
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    command: "--log-level 10 -r rise -e storakrabban -s camera/thermal/0 --ip-address 192.168.3.12 --camera-thermal"
    
